/** Mã quyền (QLPK.DataBaseAccess/Constants/PermissionCodes.cs). */
export const PERMISSION = {
  AppointmentsManage: 'appointments.manage',
  AppointmentsViewOwnSchedule: 'appointments.view_own_schedule',
  AppointmentsCheckInAssist: 'appointments.checkin_assist',
  ServicesManage: 'services.manage',
  DiscountApplyWithinThreshold: 'discount.apply_within_threshold',
  DiscountApproveOverThreshold: 'discount.approve_over_threshold',
  PromotionsManage: 'promotions.manage',
  SettingsManage: 'settings.manage',
  AccountsManageStaff: 'accounts.manage_staff',
  ExaminationsPerform: 'examinations.perform',
  ReportsView: 'reports.view',
  PatientsManage: 'patients.manage',
  DoctorTimeOffReportOwn: 'doctor_time_off.report_own',
  StaffTimeOffReportOwn: 'staff_time_off.report_own',
  DoctorSchedulesManage: 'doctor_schedules.manage',
  DoctorSchedulesManageOwn: 'doctor_schedules.manage_own',
  AppointmentsConfirmOwn: 'appointments.confirm_own',
  AppointmentsBookFollowUp: 'appointments.book_follow_up',
} as const;
